#pragma config(Sensor, dgtl12, stopTurntable,  sensorTouch)
#pragma config(Motor,  port2,           driveMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           elevatorL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           driveMotor2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           elevatorR,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           steering,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          turnTable,     tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Camera Bot
  Team Members:S Hajosy
  Date: 12 Oct 2017
  Section:


  Task Description: This will allow remote control of camera bot


  Pseudocode:

*/
int governor = 1;		//used to reduce motor speed
task main()
{
 while(1 == 1)
 {
	motor[driveMotor1] = vexRT[Ch2]/governor;
	motor[driveMotor2] = vexRT[Ch2]/governor;
	setServo(steering, vexRT[Ch4]*-1);
	if(vexRT[Btn7U] == 1)
		{
		 motor[elevatorL] = 40;
		 motor[elevatorR] = 40;
		}
	else if(vexRT[Btn7D] == 1)
		{
		 motor[elevatorL] = -40;
		 motor[elevatorR] = -40;
		}
	else
		{
		 motor[elevatorL] = 0;
		 motor[elevatorR] = 0;
	 	}
	if(vexRT[Btn7L] == 1)
		{
		 motor[turnTable] = 20;
		}
	else if(vexRT[Btn7R] == 1)
		{
		 motor[turnTable] = -20;
		}
	else
		{
		 motor[turnTable] = 0;
		}
 }
}
